# Generated by Django 4.2.30 on 2026-05-11 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_hindi', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_url', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pooja_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PoojaOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_hindi', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes_prasad', models.BooleanField(default=False)),
                ('includes_samagri', models.BooleanField(default=False)),
                ('samagri_list', models.JSONField(blank=True, default=list)),
                ('max_participants', models.PositiveIntegerField(default=1)),
                ('thumbnail_url', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='poojas.poojacategory')),
            ],
            options={
                'db_table': 'pooja_offerings',
            },
        ),
    ]
