# Generated by Django 4.2.30 on 2026-05-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_hindi', models.CharField(blank=True, default='', max_length=255)),
                ('location_description', models.TextField(blank=True, default='')),
                ('camera_type', models.CharField(choices=[('public', 'Public'), ('vip', 'VIP'), ('pooja_mandap', 'Pooja Mandap'), ('aarti', 'Aarti'), ('crowd', 'Crowd')], default='public', max_length=30)),
                ('stream_url_hls', models.TextField(blank=True, default='')),
                ('stream_url_rtmp', models.TextField(blank=True, default='')),
                ('youtube_live_url', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_live', models.BooleanField(default=False)),
                ('requires_booking', models.BooleanField(default=False)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'camera_feeds',
            },
        ),
        migrations.CreateModel(
            name='DarshanSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_hindi', models.CharField(blank=True, default='', max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('aarti', 'Aarti'), ('snan', 'Snan'), ('pooja', 'Pooja'), ('procession', 'Procession'), ('special', 'Special')], default='aarti', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_free', models.BooleanField(default=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='live_stream.camerafeed')),
            ],
            options={
                'db_table': 'darshan_schedules',
            },
        ),
        migrations.CreateModel(
            name='VIPDarshanBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_data', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_bookings', to='live_stream.darshanschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_darshan_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vip_darshan_bookings',
            },
        ),
    ]
