# Generated by Django 4.2.30 on 2026-05-11 16:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunditProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('languages_spoken', models.JSONField(blank=True, default=list)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('govid_type', models.CharField(blank=True, default='', max_length=50)),
                ('govid_number', models.CharField(blank=True, default='', max_length=100)),
                ('govid_document_url', models.TextField(blank=True, default='')),
                ('certificate_url', models.TextField(blank=True, default='')),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_poojas_done', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pundits_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pundit_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pundit_profiles',
            },
        ),
        migrations.CreateModel(
            name='PunditReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pundit_reviews', to='bookings.poojabooking')),
                ('pundit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pundits.punditprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pundit_reviews',
            },
        ),
    ]
