# Generated by Django 4.2.30 on 2026-05-11 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poojas', '0001_initial'),
        ('live_stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandapLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_hindi', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('ghat_name', models.CharField(blank=True, default='', max_length=255)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mandap_locations',
            },
        ),
        migrations.CreateModel(
            name='PoojaBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('sankalp_name', models.CharField(blank=True, default='', max_length=255)),
                ('sankalp_gotra', models.CharField(blank=True, default='', max_length=100)),
                ('sankalp_city', models.CharField(blank=True, default='', max_length=100)),
                ('sankalp_occasion', models.CharField(blank=True, default='', max_length=255)),
                ('sankalp_notes', models.TextField(blank=True, default='')),
                ('participant_count', models.PositiveIntegerField(default=1)),
                ('participant_names', models.JSONField(blank=True, default=list)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('samagri_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('no_show', 'No show')], default='pending', max_length=30)),
                ('qr_code_data', models.TextField(blank=True, default='')),
                ('qr_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('stream_access_token', models.TextField(blank=True, default='')),
                ('stream_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pundit_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pooja_bookings',
            },
        ),
        migrations.CreateModel(
            name='PoojaSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('max_bookings', models.PositiveIntegerField(default=1)),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pooja_slots', to='live_stream.camerafeed')),
                ('mandap_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pooja_slots', to='bookings.mandaplocation')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='poojas.poojaoffering')),
            ],
            options={
                'db_table': 'pooja_slots',
            },
        ),
    ]
