# Generated by Django 4.2.30 on 2026-05-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('pundits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojaslot',
            name='pundit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='pundits.punditprofile'),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='qr_scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.poojaslot'),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooja_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='poojaslot',
            constraint=models.UniqueConstraint(fields=('pundit', 'date', 'start_time'), name='uniq_pundit_date_start'),
        ),
    ]
